### ISSUE TITLE
Jcenter Bintray is down

### ISSUE THREAD

**Issue by greenbourne277** [gfelbing/konfig#10]
The library is no longer reachable under https://jcenter.bintray.com/de/gfelbing/konfig-core/0.3.4/konfig-core-0.3.4.jar'
It seems that jcenter became deprecated (https://testfairy.com/blog/jcenter-and-bintray-is-shutting-down-what-to-do/)

Could you upload it to the mavencentral repo?

Best,
Christian

**Comment by greenbourne277** [comment]
https://jitpack.io/ might be an alternative as well.

**Comment by gfelbing** [comment]
Thanks for submitting!

Since v0.4.0, konfig is available on mavenCentral: https://repo1.maven.org/maven2/io/github/gfelbing/konfig-core/0.4.0/
